version: '3.5'

services:
    postgres:
        container_name: postgres_desafio_fundecc
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: /data/postgres
        ports:
            - "5433:5432"
        networks:
            - postgres-network
        restart: unless-stopped

networks:
    postgres-network:
        driver: bridge